// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("FsYaml")>]
[<assembly: AssemblyProductAttribute("FsYaml")>]
[<assembly: AssemblyDescriptionAttribute("Type safe Yaml library for F#.")>]
[<assembly: AssemblyVersionAttribute("2.1.0")>]
[<assembly: AssemblyFileVersionAttribute("2.1.0")>]
[<assembly: InternalsVisibleToAttribute("FsYaml.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsYaml"
    let [<Literal>] AssemblyProduct = "FsYaml"
    let [<Literal>] AssemblyDescription = "Type safe Yaml library for F#."
    let [<Literal>] AssemblyVersion = "2.1.0"
    let [<Literal>] AssemblyFileVersion = "2.1.0"
    let [<Literal>] InternalsVisibleTo = "FsYaml.Tests"
